/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Microsoft Windows
 */
public class bangphieumuon extends javax.swing.JFrame {

    /**
     * Creates new form bangphieumuon
     */
    public bangphieumuon() {
        initComponents();setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfmaphieumuon = new javax.swing.JTextField();
        tfmabandoc = new javax.swing.JTextField();
        tfmanhanvien = new javax.swing.JTextField();
        them = new javax.swing.JButton();
        btntonghop = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfngaymuon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bảng Phiếu  Mượn");

        jLabel2.setText("Mã Phiếu Mượn");

        jLabel3.setText("Mã Bạn Đọc");

        jLabel4.setText("Mã Nhân Viên");

        tfmaphieumuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmaphieumuonActionPerformed(evt);
            }
        });

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        btntonghop.setText("Tổng Hợp");
        btntonghop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntonghopActionPerformed(evt);
            }
        });

        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày Mượn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btntonghop)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(them))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfmabandoc)
                            .addComponent(tfmaphieumuon)
                            .addComponent(tfmanhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(tfngaymuon))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfmaphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfmabandoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(btntonghop)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void themmuontra(){
        try {
            Connection connection = DBConnection.getConnection();
            String query = "Insert into dbo.phieumuon20173329( maphieumuon20173329 , mabandoc20173329 , manhanvien20173329, ngaymuon20173329 )"+"values(?,?,?,?)";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfmaphieumuon.getText());
            ps.setString(2, tfmabandoc.getText());
            ps.setString(3, tfmanhanvien.getText());
            ps.setString(4, tfngaymuon.getText());
            ps.executeUpdate();
            DBConnection.closeConnection(connection);
            JOptionPane.showMessageDialog(null, "them thanh cong");
                        
        } catch (SQLException ex) {
            Logger.getLogger(bangphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }

}
private boolean checktrungmaphieumuon(){
        try {
            Connection connection = DBConnection.getConnection();
            String query = " Select * from dbo.phieumuon20173329 where maphieumuon20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfmaphieumuon.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
             return true;
                
            }DBConnection.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(bangphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }
    return false;
        
}
private boolean checkcomanhanvien(){
        try {
            Connection connection = DBConnection.getConnection();
            String query = " Select * from dbo.nhanvien20173329 where manhanvien20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfmanhanvien.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
             return false;
                
            }DBConnection.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(bangphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }
    return true;
        
}

private boolean checkcomabandoc(){
        try {
            Connection connection = DBConnection.getConnection();
            String query = " Select * from dbo.bandoc20173329 where mabandoc20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfmabandoc.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
             return false;
                
            }DBConnection.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(bangphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }
    return true;
        
}
    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        try {
            // TODO add your handling code here:

            
            String maphieumuon =tfmaphieumuon.getText();
            
            if(maphieumuon.length()!=5){JOptionPane.showMessageDialog(null, "ma phieu muon phai co dinh dang PMxxx");return;}
            else{
            String a1=tfmaphieumuon.getText(0, 2);
            boolean b1=a1.equals("PM");
            boolean b2=Character.isDigit(maphieumuon.charAt(2));
            boolean b3=Character.isDigit(maphieumuon.charAt(3));
            boolean b4=Character.isDigit(maphieumuon.charAt(4));
            if((b1&&b2&&b3&&b4)==false){JOptionPane.showMessageDialog(null, "ma phieu muon phai co dinh dang PMxxx");return;}
            }
            
            
            if(tfmabandoc.getText().equals("")){JOptionPane.showMessageDialog(null, "ma ban doc khong duoc rong"); return;}else
                if(tfmanhanvien.getText().equals("")){JOptionPane.showMessageDialog(null, "manhan vien khong duoc rong");return;}else
                    if(tfmaphieumuon.getText().equals("")){JOptionPane.showMessageDialog(null, "manhan phieu muonkhong duoc rong");return;}else
                        if(tfngaymuon.getText().equals("")){JOptionPane.showMessageDialog(null, "ngay muon khong duoc rong");}
                        if(checktrungmaphieumuon()){JOptionPane.showMessageDialog(null, "trung ma phieu muon");return;}
                        else if(checkcomanhanvien()){JOptionPane.showMessageDialog(null, "ma nhan vien khong ton tai");return;}
                        else if(checkcomabandoc()){JOptionPane.showMessageDialog(null, "ma ban doc khong ton tai");return;}
                        
                        else {themmuontra();
                       new GDMuonTra().setVisible(true);}
        } catch (BadLocationException ex) {
            Logger.getLogger(bangphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_themActionPerformed

    private void btntonghopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntonghopActionPerformed
        // TODO add your handling code here:
        new GDbangphieumuon().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btntonghopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new GDQLBanDoc().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfmaphieumuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmaphieumuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmaphieumuonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bangphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bangphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bangphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bangphieumuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bangphieumuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntonghop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfmabandoc;
    private javax.swing.JTextField tfmanhanvien;
    private javax.swing.JTextField tfmaphieumuon;
    private javax.swing.JTextField tfngaymuon;
    private javax.swing.JButton them;
    // End of variables declaration//GEN-END:variables
}
