/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DBConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Microsoft Windows
 */
public class GDMuonTra extends javax.swing.JFrame implements ActionListener{
    private String query;

    /**
     * Creates new form GDMuonTra
     */
    public GDMuonTra() {
        initComponents();
        btnQuayLai.addActionListener(this);
        this.setLocationRelativeTo(null);
       loadcomobox();
        acction();
    }
 public void loadcomobox(){
        try {
            Connection connection = DBConnection.getConnection();
            PreparedStatement ps=connection.prepareStatement("SELECT BS.MASACH20173329 , BS.TENSACH20173329 FROM DBO.BANGSACH20173329 AS BS  WHERE BS.MASACH20173329 NOT IN (SELECT BS.MASACH20173329 FROM DBO.BANGSACH20173329 AS BS , DBO.CHITIETMUON20173329 WHERE  BS.MASACH20173329=CHITIETMUON20173329.MASACH20173329)");
        ResultSet rs=ps.executeQuery();
            while (rs.next()) {
                jComboBox2.addItem(rs.getString("masach20173329")+"  "+rs.getString("tensach20173329"));
                
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfmaphieumuon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNgayMuon = new javax.swing.JTextField();
        tfNgayTra = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMain = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tftiencoc = new javax.swing.JTextField();
        tftienphat = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        jButton3.setText("jButton3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nhap Thong Tin Day Du Cua Phieu Muon");

        jLabel2.setText("Mã Phiếu Mượn");

        jLabel3.setText("Mã Sách");

        tfmaphieumuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmaphieumuonActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày Mượn");

        jLabel5.setText("Ngày Trả");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        tableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableMain);

        jLabel6.setText("Tiền Cọc");

        jLabel7.setText("Tiền Phạt");

        tftiencoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftiencocActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ma Sach" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfmaphieumuon, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(tfNgayMuon)
                            .addComponent(tfNgayTra)
                            .addComponent(tftiencoc)
                            .addComponent(tftienphat)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(139, 139, 139)
                                .addComponent(btnQuayLai)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfmaphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tftiencoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tftienphat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnQuayLai))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfmaphieumuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmaphieumuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmaphieumuonActionPerformed
private void showDuLieu(){
        try {
            tableMain.removeAll();
            String[] arr={"Maphieumuon","Masach","Ngay Muon","Ngay Tra","tien coc","tien phat"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.chitietmuon20173329";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MAphieumuon20173329"));
                vector.add(rs.getString("MAsach20173329"));
                vector.add(rs.getString("NGAYMUON20173329"));
                vector.add(rs.getString("NGAYTRA20173329"));
                  vector.add(rs.getString("tiencoc20173329"));
                    vector.add(rs.getString("tienphat20173329"));
                model.addRow(vector);
            }
            
            tableMain.setModel(model);
            tableMain.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (tableMain.getSelectedRow() >=0) {
                        tfmaphieumuon.setText(tableMain.getValueAt(tableMain.getSelectedRow(), 0)+"");
                         jComboBox2.setSelectedItem(tableMain.getModel().getValueAt(tableMain.getSelectedRow(),1)+"");
                          
                            tfNgayMuon.setText(tableMain.getValueAt(tableMain.getSelectedRow(), 2)+"");
                              tfNgayTra.setText(tableMain.getValueAt(tableMain.getSelectedRow(), 3)+"");
                        tftiencoc.setText(tableMain.getValueAt(tableMain.getSelectedRow(), 4)+"");
                          tftienphat.setText(tableMain.getValueAt(tableMain.getSelectedRow(), 5)+"");
                    }
                }
            });
        } catch (SQLException ex) {
            Logger.getLogger(GDMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showDuLieu();
    }//GEN-LAST:event_formComponentShown
private void reset(){
    try {
            Connection connection = DBConnection.getConnection();
            
            String query="SELECT TOP 1 * FROM dbo.PHIEUMUON20173329 ORDER BY ID DESC";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){tfmaphieumuon.setText(rs.getString("maphieumuon20173329"));
            tfNgayMuon.setText(rs.getString("ngaymuon20173329"));}
        } catch (SQLException ex) {
            Logger.getLogger(GDMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }


tfNgayTra.setText("");

tftiencoc.setText("");
tftienphat.setText("");
}private void checktimkiemmaphieumuon(){
      try {  
            String[] arr={"Maphieumuon","Masach","Ngay Muon","Ngay Tra","tien coc","tien phat"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.chitietmuon20173329 where MAphieumuon20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1,tfmaphieumuon.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               
                Vector vector = new Vector();
                vector.add(rs.getString("MAphieumuon20173329"));
                vector.add(rs.getString("MAsach20173329"));
                vector.add(rs.getString("NGAYMUON20173329"));
                vector.add(rs.getString("NGAYTRA20173329"));
                  vector.add(rs.getString("tiencoc20173329"));
                    vector.add(rs.getString("tienphat20173329"));
                
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach.class.getName()).log(Level.SEVERE, null, ex);
        }}
private boolean checktrungmaphieumuon(){
        try {
            String co = (String) jComboBox2.getSelectedItem();
            String ba[]=co.split(" ");
            Connection connection = DBConnection.getConnection();
            String query = " Select * from dbo.chitietmuon20173329 where masach20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, ba[0]);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
             return true;
                
            }DBConnection.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(bangphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }
    return false;
        
}




    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
      String co = (String) jComboBox2.getSelectedItem();
            String ba[]=co.split(" ");
        if(tfmaphieumuon.getText().equals("")){
    JOptionPane.showMessageDialog(null, "ma ssach khong duoc rong");tfmaphieumuon.requestFocus();
return;
}else if(tfNgayMuon.getText().equals("")){
JOptionPane.showMessageDialog(null, "ngay muon khong duco rong");tfNgayMuon.requestFocus();
return;}
else if(checktrungmaphieumuon()==true){JOptionPane.showMessageDialog(null, "trung ma phieu muon");}
else if(tfNgayTra.getText().equals("")){
JOptionPane.showMessageDialog(null, "ngay hen tra khong duoc rong");
tfNgayTra.requestFocus();
return;}
else {
    try {
        String a = (String) jComboBox2.getSelectedItem();
        String b[] =a.split(" ");
        Connection connection =  DBConnection.getConnection();
        String query = " INSERT INTO dbo.chitietmuon20173329(maphieumuon20173329,MAsach20173329,NGAYMUON20173329,NGAYTRA20173329,tiencoc20173329,tienphat20173329)"+"Values(?,?,?,?,?,?)";
        PreparedStatement ps = connection.prepareStatement(query);
        ps.setString(1, tfmaphieumuon.getText());
        ps.setString(2, b[0]);
        ps.setString(3, tfNgayMuon.getText());
        ps.setString(4, tfNgayTra.getText());
        ps.setString(5, tftiencoc.getText());
        ps.setString(6, tftienphat.getText());
        ps.executeUpdate();
        showDuLieu();
        DBConnection.closeConnection(connection);
        loadcomobox();
        JOptionPane.showMessageDialog(null, "them thanh cong");
        reset();
    } catch (SQLException ex) {
        Logger.getLogger(GDMuonTra1.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}

        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
new bangphieumuon().setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_btnQuayLaiActionPerformed

    
    public void xuathoadon(int idhd){
        try {
            Hashtable map = new Hashtable();
     Connection con = DBConnection.getConnection();
            JasperReport report = JasperCompileManager.compileReport("C:\\Users\\Microsoft Windows\\Documents\\SQL Compare\\QLTV\\src\\report\\HoaDon.jrxml");
        map.put("PHIEUMUON20173329_id", idhd);
            JasperPrint p = JasperFillManager.fillReport(report, map,con);
            JasperViewer.viewReport(p,false);
        } catch (JRException ex) {
            Logger.getLogger(GDMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            Connection connection = DBConnection.getConnection();
            
            String query = "SELECT * FROM dbo.phieumuon20173329 where maphieumuon20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1,tfmaphieumuon.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               
               int a;
                a = rs.getInt("id");
              
                xuathoadon(a);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(GDMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tftiencocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftiencocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftiencocActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDMuonTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tableMain;
    private javax.swing.JTextField tfNgayMuon;
    private javax.swing.JTextField tfNgayTra;
    private javax.swing.JTextField tfmaphieumuon;
    private javax.swing.JTextField tftiencoc;
    private javax.swing.JTextField tftienphat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     if(  e.getSource().equals(btnQuayLai)){
     
     this.dispose();
     }
    }
    
    public void acction(){
        try {
            Connection connection = DBConnection.getConnection();
            
            String query="SELECT TOP 1 * FROM dbo.PHIEUMUON20173329 ORDER BY ID DESC";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){tfmaphieumuon.setText(rs.getString("maphieumuon20173329"));
            tfNgayMuon.setText(rs.getString("ngaymuon20173329"));}
        } catch (SQLException ex) {
            Logger.getLogger(GDMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
}
}
