/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DBConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Microsoft Windows
 */
public class GDMuonTra11 extends javax.swing.JFrame implements ActionListener{
    private String query;

    /**
     * Creates new form GDMuonTra
     */
    public GDMuonTra11() {
        initComponents();
        btnQuayLai.addActionListener(this);
        this.setLocationRelativeTo(null);
        load();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfmaphieumuon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNgayMuon = new javax.swing.JTextField();
        tfNgayTra = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMain = new javax.swing.JTable();
        btnreset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tftiencoc = new javax.swing.JTextField();
        tftienphat = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tfmasach = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        jButton3.setText("jButton3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bảng Mượn Trả");

        jLabel2.setText("Mã Phiếu Mượn");

        jLabel3.setText("Mã Sách");

        tfmaphieumuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmaphieumuonActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày Mượn");

        jLabel5.setText("Ngày Trả");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lai");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        tableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableMain);

        btnreset.setText("reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jLabel6.setText("Tiền Cọc");

        jLabel7.setText("Tiền Phạt");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm Kiếm");

        jButton1.setText("Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfmaphieumuon, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(tfNgayMuon)
                                    .addComponent(tfNgayTra)
                                    .addComponent(tftiencoc)
                                    .addComponent(tfmasach)
                                    .addComponent(tftienphat, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addComponent(btnreset)
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuayLai)))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfmaphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfmasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tftiencoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tftienphat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnreset)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addComponent(btnSua)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnQuayLai))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfmaphieumuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmaphieumuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmaphieumuonActionPerformed
private void showDuLieu(){
        try {
            tableMain.removeAll();
            String[] arr={"Maphieumuon","Masach","Ngay Muon","Ngay Tra","tien coc","tien phat"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.chitietmuon20173329";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MAphieumuon20173329"));
                vector.add(rs.getString("MAsach20173329"));
                vector.add(rs.getString("NGAYMUON20173329"));
                vector.add(rs.getString("NGAYTRA20173329"));
                  vector.add(rs.getString("tiencoc20173329"));
                    vector.add(rs.getString("tienphat20173329"));
                model.addRow(vector);
            }
            tableMain.setModel(model);
              tableMain.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (tableMain.getSelectedRow()>=0) {
                        tfmaphieumuon.setText(tableMain.getValueAt(tableMain.getSelectedRow(),0)+"");
                       tfmasach.setText(tableMain.getValueAt(tableMain.getSelectedRow(), 1)+"");
                        tfNgayMuon.setText(tableMain.getValueAt(tableMain.getSelectedRow(),2)+"");
                        tfNgayTra.setText(tableMain.getValueAt(tableMain.getSelectedRow(),3)+"");
                        tftiencoc.setText(tableMain.getValueAt(tableMain.getSelectedRow(),4)+"");
                        tftienphat.setText(tableMain.getValueAt(tableMain.getSelectedRow(),5)+"");
                    }
                }
            });
            
            
        } catch (SQLException ex) {
            Logger.getLogger(GDMuonTra11.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showDuLieu();
    }//GEN-LAST:event_formComponentShown
private boolean checktrungmaphieumuon(){
        try {
            Connection connection = DBConnection.getConnection();
            String query = " Select * from dbo.chitietmuon20173329 where masach20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfmasach.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
             return true;
                
            }DBConnection.closeConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(bangphieumuon.class.getName()).log(Level.SEVERE, null, ex);
        }
    return false;
        
}private void reset(){
tfmasach.setText("");
tfmaphieumuon.setText("");
tfNgayTra.setText("");
tfNgayMuon.setText("");
tftiencoc.setText("");
tftienphat.setText("");
}
 
    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
 if(tfmaphieumuon.getText().equals("")){JOptionPane.showMessageDialog(null, "nhap ma phieu muon");}
 else{
        int position = tableMain.getSelectedRow();
            String data=tableMain.getModel().getValueAt(position, 0).toString();
             String data1=tableMain.getModel().getValueAt(position, 1).toString();
              
         try {
            // TODO add your handling code here:
            
            Connection connection = DBConnection.getConnection();
            if(tfNgayTra.getText().equals("")){
            
            }else{
            String query="UPDATE DBO.chitietmuon20173329 SET ngaytra20173329=?,tiencoc20173329=?,tienphat20173329=?  WHERE MAphieumuon20173329=? and masach20173329=? ";
            PreparedStatement ps = connection.prepareStatement(query);
    
        ps.setString(1, tfNgayTra.getText());
        ps.setString(2, tftiencoc.getText());
        ps.setString(3, tftienphat.getText());
            
                ps.setString(4, data);
                ps.setString(5, tfmasach.getText());
            
                
                 ps.executeUpdate();
            
          
            
            showDuLieu();
            DBConnection.closeConnection(connection);
            JOptionPane.showMessageDialog(null, "sua thanh cong");}
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Khong The Sua Ma Phieu Muon");
        }
        
 }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed
private void checktimkiemmaphieumuon(){
      try {  
            String[] arr={"Maphieumuon","Masach","Ngay Muon","Ngay Tra","tien coc","tien phat"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.chitietmuon20173329 where MAphieumuon20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1,tfmaphieumuon.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               
                Vector vector = new Vector();
                vector.add(rs.getString("MAphieumuon20173329"));
                vector.add(rs.getString("MAsach20173329"));
                vector.add(rs.getString("NGAYMUON20173329"));
                vector.add(rs.getString("NGAYTRA20173329"));
                  vector.add(rs.getString("tiencoc20173329"));
                    vector.add(rs.getString("tienphat20173329"));
                
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach.class.getName()).log(Level.SEVERE, null, ex);
        }}
private void checktimkiemngaymuon(){
      try {  
            String[] arr={"Maphieumuon","Masach","Ngay Muon","Ngay Tra","tien coc","tien phat"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.chitietmuon20173329 where ngaymuon20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1,tfNgayMuon.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               
                Vector vector = new Vector();
                vector.add(rs.getString("MAphieumuon20173329"));
                vector.add(rs.getString("MAsach20173329"));
                vector.add(rs.getString("NGAYMUON20173329"));
                vector.add(rs.getString("NGAYTRA20173329"));
                  vector.add(rs.getString("tiencoc20173329"));
                    vector.add(rs.getString("tienphat20173329"));
                
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach.class.getName()).log(Level.SEVERE, null, ex);
        }}




    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
      reset();
      showDuLieu();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed
public void load(){
jComboBox1.addItem("tim kiem theo maphieumuon");

jComboBox1.addItem("tim kiem theo ngaymuon");


}
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       String a=(String) jComboBox1.getSelectedItem();
      
       if(a.equals("tim kiem theo maphieumuon")){
           if(tfmaphieumuon.getText().equals("")){
               JOptionPane.showMessageDialog(null, "chua nhap ten ban tim kiem"); return;}
       else{checktimkiemmaphieumuon();return;}
       }
       else if (a.equals("tim kiem theo ngaymuon")){
           if (tfNgayMuon.getText().equals("")){JOptionPane.showMessageDialog(null, "chua nhap ngay muon ban can tim kiem"); return;
          
               
           }else{checktimkiemngaymuon();return;}
       }
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
            Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.phieumuon20173329 where maphieumuon20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1,tfmaphieumuon.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               
               int a;
                a = rs.getInt("id");
              
                xuathoadon(a);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(GDMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void xuathoadon(int idhd){
        try {
            Hashtable map = new Hashtable();
     Connection con = DBConnection.getConnection();
            JasperReport report = JasperCompileManager.compileReport("C:\\Users\\Microsoft Windows\\Documents\\SQL Compare\\QLTV\\src\\report\\HoaDon.jrxml");
        map.put("PHIEUMUON20173329_id", idhd);
            JasperPrint p = JasperFillManager.fillReport(report, map,con);
            JasperViewer.viewReport(p,false);
        } catch (JRException ex) {
            Logger.getLogger(GDMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDMuonTra11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDMuonTra11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tableMain;
    private javax.swing.JTextField tfNgayMuon;
    private javax.swing.JTextField tfNgayTra;
    private javax.swing.JTextField tfmaphieumuon;
    private javax.swing.JTextField tfmasach;
    private javax.swing.JTextField tftiencoc;
    private javax.swing.JTextField tftienphat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     if(  e.getSource().equals(btnQuayLai)){
     new GDQLBanDoc().setVisible(true);
     this.dispose();
     }
    }
}
