/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Microsoft Windows
 */
public class gdThemnhanvien extends javax.swing.JFrame {

    /**
     * Creates new form gdThemnhanvien
     */
    public gdThemnhanvien() {
        initComponents();setLocationRelativeTo(null);
        
    }
private void showdulieu(){
        try {
            tablemain.removeAll();
            String []arr={"Mã Nhân Viên","Tên Nhân VIên","Địa Chỉ","Lịch Làm Việc","Tài Khoản","Mật Khẩu","Tiền Lương"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.NHANVIEN20173329";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                try {
                    Vector vector = new Vector();
                    vector.add(rs.getString("MAnhanvien20173329"));
                    vector.add(rs.getString("tennhANVIEN20173329"));
                    vector.add(rs.getString("DIACHI20173329"));
                    vector.add(rs.getString("LICHLAMVIEC20173329"));
                    vector.add(rs.getString("TAIKHOAN20173329"));
                    vector.add(rs.getString("MATKHAU20173329"));
                    vector.add(rs.getString("TIENLUONG20173329"));
                    model.addRow(vector);
                } catch (SQLException ex) {
                    Logger.getLogger(gdThemnhanvien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }tablemain.setModel(model);
            tablemain.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (tablemain.getSelectedRow()>=0) {
                        tfmanhanvien.setText(tablemain.getValueAt(tablemain.getSelectedRow(),0)+"");
                         tftennhanvien.setText(tablemain.getValueAt(tablemain.getSelectedRow(),1)+"");
                         tfdiachi.setText(tablemain.getValueAt(tablemain.getSelectedRow(),2)+"");
                          tflichlamviec.setText(tablemain.getValueAt(tablemain.getSelectedRow(),3)+"");
                           tftaikhoan.setText(tablemain.getValueAt(tablemain.getSelectedRow(),4)+"");
                            tfmatkhau.setText(tablemain.getValueAt(tablemain.getSelectedRow(),5)+"");
                             tftienluong.setText(tablemain.getValueAt(tablemain.getSelectedRow(),6)+"");
                    }
                }
            });
        } catch (SQLException ex) {
            Logger.getLogger(gdThemnhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfmanhanvien = new javax.swing.JTextField();
        tftennhanvien = new javax.swing.JTextField();
        tfdiachi = new javax.swing.JTextField();
        tflichlamviec = new javax.swing.JTextField();
        tftaikhoan = new javax.swing.JTextField();
        tfmatkhau = new javax.swing.JTextField();
        tftienluong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemain = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btndanhsach = new javax.swing.JButton();
        btnquaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Nhân Viên");

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Tên Nhân Viên");

        jLabel4.setText("Địa Chỉ");

        jLabel5.setText("Lịch Làm Việc");

        jLabel6.setText("Tài Khoản");

        jLabel7.setText("Mật Khẩu");

        jLabel8.setText("TIền Lương");

        tfmanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmanhanvienActionPerformed(evt);
            }
        });

        tftennhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftennhanvienActionPerformed(evt);
            }
        });

        tftaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftaikhoanActionPerformed(evt);
            }
        });

        tfmatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmatkhauActionPerformed(evt);
            }
        });

        tftienluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftienluongActionPerformed(evt);
            }
        });

        tablemain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablemain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemain);

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btndanhsach.setText("Danh Sách Nhân Viên");
        btndanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhsachActionPerformed(evt);
            }
        });

        btnquaylai.setText("Quay Lại");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnthem)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btndanhsach)))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnxoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(btnsua))
                            .addComponent(tfmanhanvien)
                            .addComponent(tftennhanvien)
                            .addComponent(tfdiachi)
                            .addComponent(tflichlamviec)
                            .addComponent(tftaikhoan)
                            .addComponent(tfmatkhau)
                            .addComponent(tftienluong)
                            .addComponent(btnquaylai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tftennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tflichlamviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tftaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tftienluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsua)
                            .addComponent(btnxoa)
                            .addComponent(btnthem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndanhsach)
                    .addComponent(btnquaylai))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tftaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftaikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftaikhoanActionPerformed

    private void btndanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhsachActionPerformed
showdulieu();        // TODO add your handling code here:
    }//GEN-LAST:event_btndanhsachActionPerformed

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
new GDQLnhanvien().setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnquaylaiActionPerformed
private boolean check(){
        try {
            Connection connection = DBConnection.getConnection();
            String query="Select * from dbo.nhanvien20173329 where manhanvien20173329=?";
            
            PreparedStatement ps= connection.prepareStatement(query);
            ps.setString(1, tfmanhanvien.getText());
            ResultSet rs =ps.executeQuery() ;
        
            while(rs.next()){return true;}
        } 
        catch (SQLException ex) {
            Logger.getLogger(gdThemnhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
return false;
}
private boolean checktk(){
        try {
            Connection connection = DBConnection.getConnection();
            String query="select * from dbo.nhanvien20173329 where taikhoan20173329 =?";
            PreparedStatement ps=connection.prepareStatement(query);
            ps.setString(1, tftaikhoan.getText());
            ResultSet rs=ps.executeQuery();
            while(rs.next()){return true ;}
        } catch (SQLException ex) {
            Logger.getLogger(gdThemnhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    return false;
}
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        
        try {
            if(tfmanhanvien.getText().equals("")){JOptionPane.showMessageDialog(null, "ma nv khong duoc rong");
            tfmanhanvien.requestFocus();return;}
            if(tftennhanvien.getText().equals("")){JOptionPane.showMessageDialog(null, "ten nhan vien khong duoc rong");return;}
            if(tfdiachi.getText().equals("")){JOptionPane.showMessageDialog(null, "dia chi khong duoc rong");return;}
            if(tflichlamviec.getText().equals("")){JOptionPane.showMessageDialog(null, "lic lam viec khong duoc rong");return;}else
                if(tftaikhoan.getText().equals("")){JOptionPane.showMessageDialog(null, "tai khoan khong duoc rong");return;}else
                    if(tfmatkhau.getText().equals("")){JOptionPane.showMessageDialog(null, "mat khau khong duoc rong");return;}
            if (tftienluong.getText().equals("")){JOptionPane.showMessageDialog(null, "tien luong khong duoc rong");return;}
            
       
            String manhanvien=tfmanhanvien.getText();
            if(manhanvien.length()!=5){JOptionPane.showMessageDialog(rootPane, manhanvien.length());
            JOptionPane.showMessageDialog(null, "ma nhan vien phai gom 5 ki tu");return;}
            
            String a1=tfmanhanvien.getText(0, 2);
            boolean a2=a1.equals("NV");
            boolean a3=Character.isDigit(manhanvien.charAt(2));
            boolean a4=Character.isDigit(manhanvien.charAt(3));
            boolean a5=Character.isDigit(manhanvien.charAt(4));
            if((a2&&a3&a4&&a5)==false){JOptionPane.showMessageDialog(null, "ma nhan vien phai gom 5 ki tu theo dang NVxxx");return;}
            if(checktk()==true){JOptionPane.showMessageDialog(null, "trung tai khoan"); return ;}
            if(check()==true){JOptionPane.showMessageDialog(null, "trung ma nhan vien");return;
            }else{
                
                try { Connection connection = DBConnection.getConnection();
                String query = "insert into dbo.nhanvien20173329(manhanvien20173329 ,tennhanvien20173329,diachi20173329,lichlamviec20173329,taikhoan20173329,matkhau20173329,tienluong20173329) "
                        +"values(?,?,?,?,?,?,?)";
                PreparedStatement ps =connection.prepareStatement(query);
                ps.setString(1, tfmanhanvien.getText());
                ps.setString(2, tftennhanvien.getText());
                ps.setString(3, tfdiachi.getText());
                ps.setString(4, tflichlamviec.getText());
                ps.setString(5, tftaikhoan.getText());
                ps.setString(6, tfmatkhau.getText());
                ps.setString(7, tftienluong.getText());
                ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "them thanh cong");
                showdulieu();
                DBConnection.closeConnection(connection);
                
                
                } catch (SQLException ex) {
                   ex.printStackTrace();
                }
                
                
            }
        } catch (BadLocationException ex) {
            Logger.getLogger(gdThemnhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
         
              
            

        
    }//GEN-LAST:event_btnthemActionPerformed

    private void tfmanhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmanhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmanhanvienActionPerformed

    private void tftennhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftennhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftennhanvienActionPerformed

    private void tfmatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmatkhauActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
 int result= JOptionPane.showConfirmDialog(null, "ban co chac chan xoa");
      if(result==0){
     
        try {int position = tablemain.getSelectedRow();
            String data = tablemain.getModel().getValueAt(position, 0).toString();
           Connection connection = DBConnection.getConnection();
            String query = "DELETE dbo.nhanvien20173329 WHERE MAnhanvien20173329= ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, data);
            ps.executeUpdate();
           showdulieu();
            DBConnection.closeConnection(connection);
            JOptionPane.showMessageDialog(null, "xoa thanh cong");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ban chua chon dong can xoa");
        }}        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
 if(tfmanhanvien.getText().equals("")){JOptionPane.showMessageDialog(null, "nhap ma nhan vien"); return;}
if(check()==false){JOptionPane.showMessageDialog(null, "khong ton tai ma nhan viee");return;}
 else { 
     try {
         if(tftienluong.getText().equals("")){
             JOptionPane.showMessageDialog(null, "nhap tien luong");
         return;}
         Connection connection = DBConnection.getConnection();
         String query="UPDATE DBO.nhanvien20173329 SET tienluong20173329=?  WHERE Manhanvien20173329=? ";
         PreparedStatement ps = connection.prepareStatement(query);
         ps.setString(1, tftienluong.getText());
         ps.setString(2, tfmanhanvien.getText());
         ps.executeUpdate();
         showdulieu();
         DBConnection.closeConnection(connection);
         JOptionPane.showMessageDialog(null, "sua thanh cong");
     } catch (SQLException ex) {
         Logger.getLogger(gdThemnhanvien.class.getName()).log(Level.SEVERE, null, ex);
     }
  }
 
 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsuaActionPerformed

    private void tablemainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablemainMouseClicked

    private void tftienluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftienluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftienluongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gdThemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gdThemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gdThemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gdThemnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gdThemnhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndanhsach;
    private javax.swing.JButton btnquaylai;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablemain;
    private javax.swing.JTextField tfdiachi;
    private javax.swing.JTextField tflichlamviec;
    private javax.swing.JTextField tfmanhanvien;
    private javax.swing.JTextField tfmatkhau;
    private javax.swing.JTextField tftaikhoan;
    private javax.swing.JTextField tftennhanvien;
    private javax.swing.JTextField tftienluong;
    // End of variables declaration//GEN-END:variables
}
