/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.corba.se.impl.logging.ORBUtilSystemException;
import controller.DBConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Microsoft Windows
 */
public class QuanLyBangSach11 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyBangSach11() {
        initComponents();
        setLocationRelativeTo(null);
        btnThoat.addActionListener(this);
        loadcomobox();
        loaddata1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        sad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfMaSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ddas = new javax.swing.JLabel();
        tfTacGia = new javax.swing.JTextField();
        tfTenSach = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMain = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfNXB = new javax.swing.JTextField();
        btnquaylai = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfnamxuatban = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfgiatien = new javax.swing.JTextField();
        combox = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        sad.setText("Mã Sách");

        jLabel2.setText("Thể Loại");

        jLabel3.setText("Tác Giả");

        ddas.setText("Tên Sách");

        tfTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTacGiaActionPerformed(evt);
            }
        });

        tfTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenSachActionPerformed(evt);
            }
        });

        tableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMain);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel5.setText("NXB");

        tfNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNXBActionPerformed(evt);
            }
        });

        btnquaylai.setText("Làm Mới");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("QUẢN LÝ BẢNG SÁCH");

        jLabel8.setText("Năm Xuất Bản");

        tfnamxuatban.setText(" ");

        jLabel10.setText("Giá Tiền");

        tfgiatien.setText(" ");

        combox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tim Kiem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(ddas)
                                            .addComponent(jLabel3)))
                                    .addComponent(sad))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTenSach)
                                    .addComponent(tfTacGia)
                                    .addComponent(tfnamxuatban, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(59, 59, 59)
                                .addComponent(tfgiatien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(78, 78, 78))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnquaylai)
                .addGap(102, 102, 102)
                .addComponent(btnThoat)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddas)
                            .addComponent(tfTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfnamxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfgiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat)
                    .addComponent(btnquaylai))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenSachActionPerformed

    
    
    private void showDuLieu(){
        try {
            tableMain.removeAll();
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.BANGSACH20173329";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
             tableMain.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (tableMain.getSelectedRow()>=0) {
                        tfMaSach.setText(tableMain.getValueAt(tableMain.getSelectedRow(),0)+"");
                     
                        tfTenSach.setText(tableMain.getValueAt(tableMain.getSelectedRow(),1)+"");
                        tfTacGia.setText(tableMain.getValueAt(tableMain.getSelectedRow(),2)+"");
                        tfNXB.setText(tableMain.getValueAt(tableMain.getSelectedRow(),3)+"");
                          combox.setSelectedItem(tableMain.getModel().getValueAt(tableMain.getSelectedRow(), 4)+"");
                       tfgiatien.setText(tableMain.getValueAt(tableMain.getSelectedRow(),5)+"");
                         tfnamxuatban.setText(tableMain.getValueAt(tableMain.getSelectedRow(),6)+"");
                    }
                }
            });
            
            
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    
    
    }
    public void loadcomobox(){
        try {
            Connection connection = DBConnection.getConnection();
            PreparedStatement ps=connection.prepareStatement("select theloai20173329 from dbo.bangsach20173329 group by theloai20173329");
        ResultSet rs=ps.executeQuery();
            while (rs.next()) {
                combox.addItem(rs.getString("theloai20173329"));
                
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    private void reset(){
    tfMaSach.setText("");
    tfNXB.setText("");
    tfTacGia.setText("");
    tfTenSach.setText("");
    
    tfgiatien.setText("");
    tfnamxuatban.setText("");
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showDuLieu();
    }//GEN-LAST:event_formComponentShown
private boolean checkTrungMaSach(){
        try {
            Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.BANGSACH20173329 where MASACH20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfMaSach.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }return false;
          
            
        
    
   
        
}private void checktimkiemMASACH(){
     try {
    
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where MASACH20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfMaSach.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemTenSach(){
     try {
    
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where TENSACH20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfTenSach.getText());
            ResultSet rs = ps.executeQuery();
           
            while(rs.next()){
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
             
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemTheLoai(){
     try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where THELOAI20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, (String) combox.getSelectedItem());
           
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemNXB(){
     try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where NXB20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfNXB.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemTacGia(){
      try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where TENTACGIA20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfTacGia.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}

private void checktimkiemNamXB(){
      try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where namxuatban20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfnamxuatban.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach11.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        // TODO add your handling code here:
        showDuLieu();
        reset();
    }//GEN-LAST:event_btnquaylaiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tfNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNXBActionPerformed

    private void tfTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTacGiaActionPerformed

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_comboxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String a=(String) jComboBox1.getSelectedItem();
      
       if(a.equals("Tim Kiem Theo Ten")){
           if(tfTenSach.getText().equals("")){
               JOptionPane.showMessageDialog(null, "chua nhap ten ban tim kiem"); return;}
       else{checktimkiemTenSach();return;}
       }else if(a.equals("Tim Kiem Theo MaSach")){if(tfMaSach.getText().equals("")){
       JOptionPane.showMessageDialog(null, "chua nhap masach ban tim kiem");return;}
       else{
       checktimkiemMASACH(); return;}}
       else if (a.equals("Tim Kiem Theo TacGia")){
           if (tfTacGia.getText().equals("")){JOptionPane.showMessageDialog(null, "chua nhap ten tac gia ban can tim kiem"); return;
          
               
           }else{checktimkiemTacGia();return;}
       }
       else if (a.equals("Tim Kiem Theo NXB")){
           if (tfNXB.getText().equals("")){JOptionPane.showMessageDialog(null, "chua nhap NXB an can tim kiem");return;
               
           }else{checktimkiemNXB();}
}else if (a.equals("Tim Kiem Theo TheLoai")){if(combox.getSelectedItem().equals("")){
    JOptionPane.showMessageDialog(null, "chua chon the loai"); return;}
else{checktimkiemTheLoai(); return;}}
else if(a.equals("Tim Kiem Theo NamXB")){ if (tfnamxuatban.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "chua nhap namXB ban can tim kiem"); return;
                          }else{checktimkiemNamXB();return;}
}
       reset();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyBangSach11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnquaylai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox combox;
    private javax.swing.JLabel ddas;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sad;
    private javax.swing.JTable tableMain;
    private javax.swing.JTextField tfMaSach;
    private javax.swing.JTextField tfNXB;
    private javax.swing.JTextField tfTacGia;
    private javax.swing.JTextField tfTenSach;
    private javax.swing.JTextField tfgiatien;
    private javax.swing.JTextField tfnamxuatban;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnThoat)){
        btnTrangchu();
        }
    }
    public void loaddata1(){jComboBox1.addItem("Tim Kiem Theo Ten");
    jComboBox1.addItem("Tim Kiem Theo MaSach");
    jComboBox1.addItem("Tim Kiem Theo TheLoai");
    jComboBox1.addItem("Tim Kiem Theo TacGia");
    jComboBox1.addItem("Tim Kiem Theo NXB");
    jComboBox1.addItem("Tim Kiem Theo NamXB");
    
    }
    public void btnTrangchu(){
    new GDBanDoc().setVisible(true);
    this.dispose();
    }
   
}
