/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.corba.se.impl.logging.ORBUtilSystemException;
import controller.DBConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Microsoft Windows
 */
public class QuanLyBangSach1 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyBangSach1() {
        initComponents();
        setLocationRelativeTo(null);
        btnThoat.addActionListener(this);
        loadcomobox();
        loaddata1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        sad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfMaSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ddas = new javax.swing.JLabel();
        tfTacGia = new javax.swing.JTextField();
        tfTenSach = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMain = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfNXB = new javax.swing.JTextField();
        btnquaylai = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfnamxuatban = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfgiatien = new javax.swing.JTextField();
        combox = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        sad.setText("Mã Sách");

        jLabel2.setText("Thể Loại");

        jLabel3.setText("Tác Giả");

        ddas.setText("Tên Sách");

        tfTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTacGiaActionPerformed(evt);
            }
        });

        tfTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenSachActionPerformed(evt);
            }
        });

        tableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMain);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel5.setText("NXB");

        tfNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNXBActionPerformed(evt);
            }
        });

        btnquaylai.setText("Làm Mới");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("QUẢN LÝ BẢNG SÁCH");

        jLabel8.setText("Năm Xuất Bản");

        tfnamxuatban.setText(" ");

        jLabel10.setText("Giá Tiền");

        tfgiatien.setText(" ");

        combox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tìm Kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ddas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(sad))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTenSach)
                                    .addComponent(tfTacGia)
                                    .addComponent(tfnamxuatban)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnThem)
                                        .addGap(81, 81, 81)
                                        .addComponent(btnXoa)
                                        .addGap(112, 112, 112)
                                        .addComponent(btnquaylai)
                                        .addGap(84, 84, 84)
                                        .addComponent(btnThoat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfNXB)
                                            .addComponent(tfgiatien)
                                            .addComponent(combox, 0, 178, Short.MAX_VALUE))))
                                .addGap(0, 187, Short.MAX_VALUE)))
                        .addGap(78, 78, 78))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1)
                                .addGap(59, 59, 59)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddas)
                            .addComponent(tfTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfnamxuatban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfgiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnquaylai)
                    .addComponent(btnThoat))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenSachActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int result=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn không ? Khi có Mã Sách sẽ bị xóa trong hệ thống Mượn Trả ");
        if(result==0){
    
        int position = tableMain.getSelectedRow();
        String data = tableMain.getModel().getValueAt(position, 0).toString();
      
         try {
              
            Connection connection = DBConnection.getConnection();
            String query="DELETE FROM DBO.chitietmuon20173329 WHERE MASACH20173329=?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, data);
            ps.executeUpdate();
            
          
           
               
               String query1 = "DELETE dbo.[BANGSACH20173329] WHERE MASACH20173329= ?";
                       
               PreparedStatement ps1 = connection.prepareStatement(query1);
               ps1.setString(1,data);
          
               ps1.executeUpdate();
               showDuLieu();
               DBConnection.closeConnection(connection);
               JOptionPane.showMessageDialog(null, "xoa thanh cong");
           } catch (SQLException ex) {
             ex.printStackTrace();
           }}
        
    }//GEN-LAST:event_btnXoaActionPerformed

    
    
    private void showDuLieu(){
        try {
            tableMain.removeAll();
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.BANGSACH20173329";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
             tableMain.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (tableMain.getSelectedRow()>=0) {
                        tfMaSach.setText(tableMain.getValueAt(tableMain.getSelectedRow(),0)+"");
                     
                        tfTenSach.setText(tableMain.getValueAt(tableMain.getSelectedRow(),1)+"");
                        tfTacGia.setText(tableMain.getValueAt(tableMain.getSelectedRow(),2)+"");
                        tfNXB.setText(tableMain.getValueAt(tableMain.getSelectedRow(),3)+"");
                          combox.setSelectedItem(tableMain.getModel().getValueAt(tableMain.getSelectedRow(), 4)+"");
                       tfgiatien.setText(tableMain.getValueAt(tableMain.getSelectedRow(),5)+"");
                         tfnamxuatban.setText(tableMain.getValueAt(tableMain.getSelectedRow(),6)+"");
                    }
                }
            });
            
            
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    
    
    }
    public void loadcomobox(){
        try {
            Connection connection = DBConnection.getConnection();
            PreparedStatement ps=connection.prepareStatement("select theloai20173329 from dbo.bangsach20173329 group by theloai20173329");
        ResultSet rs=ps.executeQuery();
            while (rs.next()) {
                combox.addItem(rs.getString("theloai20173329"));
                
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    private void reset(){
    tfMaSach.setText("");
    tfNXB.setText("");
    tfTacGia.setText("");
    tfTenSach.setText("");
    
    tfgiatien.setText("");
    tfnamxuatban.setText("");
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showDuLieu();
    }//GEN-LAST:event_formComponentShown
private boolean checkTrungMaSach(){
        try {
            Connection connection = DBConnection.getConnection();
            String query = "SELECT * FROM dbo.BANGSACH20173329 where MASACH20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfMaSach.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }return false;
          
            
        
    
   
        
}
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
   
        if(tfMaSach.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "maSAch chua thanh cong");
       tfMaSach.requestFocus();
       return;
       }
       else if(tfTacGia.getText().equals("")){
       JOptionPane.showMessageDialog(rootPane, "TAC GIa chua thanh cong");
       tfTacGia.requestFocus();
       return;}
       else if(tfNXB.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane, "NXB chua thanh cong");
        tfNXB.requestFocus();
       return;}
       else if (tfTenSach.getText().equals("")){
       JOptionPane.showMessageDialog(rootPane, "TEN Sach chua thanh cong");
        tfTenSach.requestFocus();
       return;}
       else if(tfgiatien.getText().equals("")){JOptionPane.showMessageDialog(null, "them gia tien chua thanh cong");
       return;}
       else if(tfnamxuatban.getText().equals("")){JOptionPane.showMessageDialog(null, "them nam xuat ban thanh cong");
       return;}
       String masach=tfMaSach.getText();
       if(masach.length()!=5){
       JOptionPane.showMessageDialog(rootPane, "ma sach phai co 5 ki tu");
       tfMaSach.requestFocus();
       return;}
        try {
            String a1=tfMaSach.getText(0, 2);
            boolean a5=a1.equals("MS");
            boolean a2=Character.isDigit(masach.charAt(2));
            boolean a3=Character.isDigit(masach.charAt(3));
              boolean a4=Character.isDigit(masach.charAt(4));
              if((a2&&a3&&a4&&a5)==false){
                  JOptionPane.showMessageDialog(null, "nhap sai dinh dang mssach MSxxx");
                  return;
              }
        } catch (BadLocationException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      if(checkTrungMaSach()==true){
          JOptionPane.showMessageDialog(null,"ma sach da ton tai");
          tfMaSach.requestFocus();
          return;
          
      }
             
          try {
               Connection connection = DBConnection.getConnection();
               String query = "INSERT INTO dbo.[BANGSACH20173329](MASACH20173329, TENSACH20173329 , THELOAI20173329, TENTACGIA20173329, NXB20173329,giatien20173329,namxuatban20173329) "+
                       "VALUES(?,?,?,?,?,?,?)";
               PreparedStatement ps = connection.prepareStatement(query);
               ps.setString(1, tfMaSach.getText());
               ps.setString(2, tfTenSach.getText());
               ps.setString(3, (String)combox.getSelectedItem());
               ps.setString(4, tfTacGia.getText());
                ps.setString(5, tfNXB.getText());
               
                  ps.setString(6, tfgiatien.getText());
                    ps.setString(7, tfnamxuatban.getText());
               ps.executeUpdate();
               showDuLieu();
               DBConnection.closeConnection(connection);
               JOptionPane.showMessageDialog(null, "them thanh cong");
               reset();
           } catch (SQLException ex) {
             ex.printStackTrace();
           }
             
             
             
       
    }//GEN-LAST:event_btnThemActionPerformed
private void checktimkiemMASACH(){
     try {
    
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where MASACH20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfMaSach.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemTenSach(){
     try {
    
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where TENSACH20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfTenSach.getText());
            ResultSet rs = ps.executeQuery();
           
            while(rs.next()){
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
             
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemTheLoai(){
     try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where THELOAI20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, (String) combox.getSelectedItem());
           
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemNXB(){
     try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where NXB20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfNXB.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
private void checktimkiemTacGia(){
      try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where TENTACGIA20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfTacGia.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}

private void checktimkiemNamXB(){
      try {  
            String[] arr= {"Mã Sách","Tên Sách","Tên Tác Giả","NXB","Thể Loại","Gia Tien","Nam XB"};
           
            DefaultTableModel model = new DefaultTableModel(arr, 0);
             Connection connection = DBConnection.getConnection();
             String query = "SELECT * FROM dbo.BANGSACH20173329 where namxuatban20173329 = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, tfnamxuatban.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MASACH20173329"));
                vector.add(rs.getString("TENSACH20173329"));
                vector.add(rs.getString("TENTACGIA20173329"));
                vector.add(rs.getString("NXB20173329"));
                vector.add(rs.getString("THELOAI20173329"));
                  vector.add(rs.getString("GiaTien20173329"));
                    vector.add(rs.getString("NamXuatBan20173329"));
                model.addRow(vector);
            }
            DBConnection.closeConnection(connection);
            tableMain.setModel(model);
            
          
        
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBangSach1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
}
    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        // TODO add your handling code here:
        showDuLieu();
        reset();
    }//GEN-LAST:event_btnquaylaiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tfNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNXBActionPerformed

    private void tfTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTacGiaActionPerformed

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_comboxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String a=(String) jComboBox1.getSelectedItem();
      
       if(a.equals("Tim Kiem Theo Ten")){
           if(tfTenSach.getText().equals("")){
               JOptionPane.showMessageDialog(null, "chua nhap ten ban tim kiem"); return;}
       else{checktimkiemTenSach();return;}
       }else if(a.equals("Tim Kiem Theo MaSach")){if(tfMaSach.getText().equals("")){
       JOptionPane.showMessageDialog(null, "chua nhap masach ban tim kiem");return;}
       else{
       checktimkiemMASACH(); return;}}
       else if (a.equals("Tim Kiem Theo TacGia")){
           if (tfTacGia.getText().equals("")){JOptionPane.showMessageDialog(null, "chua nhap ten tac gia ban can tim kiem"); return;
          
               
           }else{checktimkiemTacGia();return;}
       }
       else if (a.equals("Tim Kiem Theo NXB")){
           if (tfNXB.getText().equals("")){JOptionPane.showMessageDialog(null, "chua nhap NXB an can tim kiem");return;
               
           }else{checktimkiemNXB();}
}else if (a.equals("Tim Kiem Theo TheLoai")){if(combox.getSelectedItem().equals("")){
    JOptionPane.showMessageDialog(null, "chua chon the loai"); return;}
else{checktimkiemTheLoai(); return;}}
else if(a.equals("Tim Kiem Theo NamXB")){ if (tfnamxuatban.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "chua nhap namXB ban can tim kiem"); return;
                          }else{checktimkiemNamXB();return;}
}
       reset();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBangSach1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyBangSach1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnquaylai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox combox;
    private javax.swing.JLabel ddas;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sad;
    private javax.swing.JTable tableMain;
    private javax.swing.JTextField tfMaSach;
    private javax.swing.JTextField tfNXB;
    private javax.swing.JTextField tfTacGia;
    private javax.swing.JTextField tfTenSach;
    private javax.swing.JTextField tfgiatien;
    private javax.swing.JTextField tfnamxuatban;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnThoat)){
        btnTrangchu();
        }
    }
    public void loaddata1(){jComboBox1.addItem("Tim Kiem Theo Ten");
    jComboBox1.addItem("Tim Kiem Theo MaSach");
    jComboBox1.addItem("Tim Kiem Theo TheLoai");
    jComboBox1.addItem("Tim Kiem Theo TacGia");
    jComboBox1.addItem("Tim Kiem Theo NXB");
    jComboBox1.addItem("Tim Kiem Theo NamXB");
    
    }
    public void btnTrangchu(){
    new GDQLnhanvien().setVisible(true);
    this.dispose();
    }
   
}
